### PR TITLE
Renaming README.txt to README.md so markdown is rendered on GitHub.

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by starit** [comment]
Why not merge... @vbuterin

**Comment by reiven** [comment]
ping

**Comment by jonathancross** [comment]
Unfortunately it looks like this project has been abandoned by @vbuterin

**Comment by jonathancross** [comment]
Unfortunately it looks like this project has been abandoned by @vbuterin

**Comment by jonathancross** [comment]
Seems the is a duplicate of #53 anyhow.

**Pull request closed without merging**
